# Generated by Django 3.2.9 on 2022-03-11 18:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('listno', models.AutoField(primary_key=True, serialize=False)),
                ('listname', models.CharField(max_length=500)),
                ('leads', models.CharField(max_length=500)),
                ('generationDate', models.DateField(auto_now_add=True)),
                ('scrapingurl', models.CharField(max_length=500)),
                ('last_updated', models.DateField(auto_now=True)),
                ('list_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leadlist',
            fields=[
                ('generationDate', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('phones', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('reviews', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('tags', models.CharField(blank=True, choices=[('grocery', 'grocery'), ('fruits', 'fruits'), ('vegetables', 'vegetables'), ('hindustan uniliver', 'hindustan uniliver')], max_length=100)),
                ('lead_status', models.CharField(blank=True, choices=[('lead', 'lead'), ('contact made', 'contact made'), ('signed up', 'signed up'), ('closed lost', 'closed lost'), ('closed won', 'closed won')], max_length=100)),
                ('list_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.list')),
                ('team', models.ManyToManyField(to='authenticate.Team')),
            ],
        ),
    ]
